# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Qwuke
email: tristan.e.mortimer+qwuke@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tristan Mortimer's personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qwu.ke" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Qwuke

# Outputting
permalink: /posts/:title:output_ext
paginate: 10 # amount of posts to show
paginate_path: /posts/page:num/
markdown: kramdown

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


